name: Convert Minecraft Icons

on:

  issues:

    types: [opened]

jobs:

  convert_icons:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code

        uses: actions/checkout@v2

      - name: Install Python

        uses: actions/setup-python@v2

        with:

          python-version: '3.9'

      - name: Install dependencies

        run: pip install pillow

      - name: Convert Minecraft icons

        run: python convert_icons.py ${{ github.event.issue.body }}

      - name: Upload converted icons

        uses: actions/upload-artifact@v2

        with:

          name: converted_icons

          path: ./output.zip

