name: Convert Minecraft 3D icons to 2D

on: 
  issues:
    types: [opened]

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y imagemagick
      
      - name: Convert icons
        run: bash convert_icons.sh ${{ github.event.issue.body }}
