name: Convert Minecraft icons

on:
  issues:
    types: [opened]

jobs:
  convert_icons:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pillow
          pip install selfupdate

      - name: Run conversion code
        run: python convert_icons.py ${{ github.event.issue.body }}
