name: Convert Minecraft 3D icons to 2D

on:
  issues:
    types: [opened]

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install python3-pip
          sudo pip3 install Pillow

      - name: Convert icons
        run: |
          git clone https://github.com/JohnOliver09/mc-item-icon-to-2d.git
          cd mc-item-icon-to-2d
          ./convert_icons.sh ${{ github.event.issue.body }}
          
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: icons
          path: output
