name: Convert Minecraft 3D Item Icons to 2D
on: issues
jobs:
  convert-icons:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Convert icons
        env:
          PACK_URL: ${{ github.event.issue.body }}
        run: |
          wget $PACK_URL -O pack.zip
          unzip pack.zip -d pack
          mkdir output
          for file in pack/assets/minecraft/textures/item/*.png
          do
            filename=$(basename -- "$file")
            filename="${filename%.*}"
            convert $file -crop 32x32+0+0 output/$filename.png
          done
          zip -r output.zip output
      - name: Upload output file
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: output.zip
